<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="2" hostname="DESKTOP-F4DEVB3" name="com.aspire.FrameWork.TestNG.KeyWords" tests="8" failures="0" timestamp="2022-11-17T12:26:54 IST" time="1.552" errors="1">
  <testcase name="method2" time="0.015" classname="com.aspire.FrameWork.TestNG.KeyWords"/>
  <system-out>
    <![CDATA[Method 2]]>
  </system-out>
  <testcase name="login" time="1.533" classname="com.aspire.FrameWork.TestNG.KeyWords">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method com.aspire.FrameWork.TestNG.KeyWords.login() didn&#039;t finish within the time-out 1500">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.aspire.FrameWork.TestNG.KeyWords.login() didn't finish within the time-out 1500
at org.testng.internal.MethodInvocationHelper.invokeWithTimeoutWithNewExecutor(MethodInvocationHelper.java:384)
at org.testng.internal.MethodInvocationHelper.invokeWithTimeout(MethodInvocationHelper.java:283)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:604)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- login -->
  <system-out/>
  <testcase name="method4" time="0.000" classname="com.aspire.FrameWork.TestNG.KeyWords"/>
  <system-out>
    <![CDATA[Method 4]]>
  </system-out>
  <testcase name="logOut" time="0.000" classname="com.aspire.FrameWork.TestNG.KeyWords">
    <skipped/>
  </testcase> <!-- logOut -->
  <system-out/>
  <testcase name="method1" time="0.003" classname="com.aspire.FrameWork.TestNG.KeyWords"/>
  <system-out>
    <![CDATA[Method 1]]>
  </system-out>
  <testcase name="method5" time="0.000" classname="com.aspire.FrameWork.TestNG.KeyWords"/>
  <system-out>
    <![CDATA[Method 5]]>
  </system-out>
  <testcase name="method1" time="0.001" classname="com.aspire.FrameWork.TestNG.KeyWords"/>
  <system-out>
    <![CDATA[Method 1]]>
  </system-out>
  <testcase name="method3" classname="com.aspire.FrameWork.TestNG.KeyWords">
    <skipped/>
  </testcase> <!-- method3 -->
  <system-out/>
</testsuite> <!-- com.aspire.FrameWork.TestNG.KeyWords -->
